import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUp, Eye, EyeOff, FileText, Image, Layers, MessageSquare, Monitor, Plus, Redo2, Save, Smartphone, Sparkles, Tablet, Trash2, Undo2, Palette, Menu } from 'lucide-react';
import { toast } from 'sonner';
import { getProducts } from '@/lib/product-store';
import { Action, Field, Modal, Pill } from './ui';
import { EditorSidebar } from './source-ui/EditorSidebar';
import { EDITOR_SIDEBAR_WIDTH, SETTINGS_PANEL_WIDTH } from './source-ui/layout-constants';
import { makeBlock, updateDraft, updateWebsite, websiteHref, type Website, type WebsiteContent, type Block, type BlockKind } from './store';
import { StorefrontPreview } from './StorefrontPreview';

export function Editor({ site, onPublish }: { site: Website; onPublish: () => void }) {
  const [tab, setTab] = useState('components');
  const [pageId, setPageId] = useState(site.draft.pages[0].id);
  const [selectedId, setSelectedId] = useState(site.draft.pages[0].blocks[1]?.id ?? '');
  const [device, setDevice] = useState('desktop');
  const [settingsTab, setSettingsTab] = useState('content');
  const [library, setLibrary] = useState(false);
  const [mediaOpen, setMediaOpen] = useState(false);
  const media = [...new Set([...site.draft.pages.flatMap(p => p.blocks.map(b => b.image)), ...getProducts().flatMap(p => p.images ?? [])])].filter(Boolean).slice(0, 36);
  const [past, setPast] = useState<WebsiteContent[]>([]);
  const [future, setFuture] = useState<WebsiteContent[]>([]);
  const [prompt, setPrompt] = useState('');
  const [aiBusy, setAiBusy] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState('');
  const [saveMessage, setSaveMessage] = useState('Draft restored');
  const page = site.draft.pages.find(p => p.id === pageId) ?? site.draft.pages[0];
  const block = page.blocks.find(b => b.id === selectedId);
  function change(edit: (draft: WebsiteContent) => WebsiteContent) {
    try { updateDraft(site.id, edit); setPast([...past.slice(-29), structuredClone(site.draft)]); setFuture([]); setSaveMessage('Draft saved locally'); } catch { toast.error('Unable to save. Browser storage may be full.'); }
  }
  function editBlock(patch: Partial<Block>) { change(d => ({ ...d, pages: d.pages.map(p => p.id === page.id || block?.kind === 'footer' ? { ...p, blocks: p.blocks.map(b => b.id === selectedId || (block?.kind === 'footer' && b.kind === 'footer') ? { ...b, ...patch } : b) } : p) })); }
  function reorder(id: string, delta: number) { change(d => { const p = d.pages.find(p => p.id === page.id)!; const index = p.blocks.findIndex(b => b.id === id); const next = index + delta; if (next >= 0 && next < p.blocks.length) [p.blocks[index], p.blocks[next]] = [p.blocks[next], p.blocks[index]]; return d; }); }
  async function upload(file: File | undefined, target: 'image' | 'logo' | 'favicon') {
    if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp', 'image/gif'].includes(file.type) || file.size > 700_000) { toast.error('Choose a PNG, JPG, WebP or GIF under 700 KB for this demo.'); return; }
    const value = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    if (target === 'image') editBlock({ image: value }); else change(d => ({ ...d, [target]: value }));
  }
  return <div className="pw-editor" style={{ '--editor-left': `${EDITOR_SIDEBAR_WIDTH}px`, '--editor-right': `${SETTINGS_PANEL_WIDTH}px` } as React.CSSProperties}>
    <div className="pw-editor-toolbar"><div className="pw-actions"><select aria-label="Current page" value={page.id} onChange={e => { setPageId(e.target.value); setSelectedId(''); }}>{site.draft.pages.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><span className="pw-muted pw-save-state" role="status">{saveMessage}</span></div><div className="pw-device-switch">{[{ id: 'desktop', icon: Monitor }, { id: 'tablet', icon: Tablet }, { id: 'mobile', icon: Smartphone }].map(({ id, icon: Icon }) => <Action key={id} aria-label={`${id} preview`} aria-pressed={device === id} onClick={() => setDevice(id)}><Icon size={17} /></Action>)}</div><div className="pw-actions"><Action aria-label="Undo" disabled={!past.length} onClick={() => { updateDraft(site.id, () => past[past.length - 1]); setFuture([site.draft, ...future]); setPast(past.slice(0, -1)); }}><Undo2 size={17} /></Action><Action aria-label="Redo" disabled={!future.length} onClick={() => { updateDraft(site.id, () => future[0]); setPast([...past, site.draft]); setFuture(future.slice(1)); }}><Redo2 size={17} /></Action><Action onClick={() => { updateWebsite(site.id, s => ({ ...s, savedAt: new Date().toISOString() })); setSaveMessage('Draft saved locally'); toast.success('Draft saved. Published website is unchanged.'); }}><Save size={16} />Save</Action><Link className="pw-button" to={websiteHref('preview', site.id)}><Eye size={16} />Preview</Link><Action primary onClick={onPublish}>{site.published ? 'Update website' : 'Publish'}</Action></div></div>
    <div className="pw-editor-grid"><EditorSidebar tabs={[{ id: 'chat', label: 'AI Chat', icon: <MessageSquare size={15} /> }, { id: 'components', label: 'Components', icon: <Layers size={15} /> }, { id: 'pages', label: 'Pages', icon: <FileText size={15} /> }]} activeTab={tab} onTabChange={setTab}>
      {tab === 'components' && <><div className="pw-panel-title"><div><strong>Page structure</strong><p>Build your page, one section at a time.</p></div></div><div className="pw-block-list">{page.blocks.map((b, i) => <div key={b.id} className={`pw-block-row ${selectedId === b.id ? 'active' : ''}`}><button type="button" className="pw-block-select" onClick={() => { setSelectedId(b.id); setSettingsTab('content'); }}><Layers size={15} /><span>{b.kind === 'image-text' ? 'Image & text' : b.kind.charAt(0).toUpperCase() + b.kind.slice(1)}</span>{!b.visible && <EyeOff size={14} />}</button><Action aria-label={`Move ${b.kind} up`} disabled={i === 0} onClick={() => reorder(b.id, -1)}><ArrowUp size={13} /></Action><Action aria-label={`Move ${b.kind} down`} disabled={i === page.blocks.length - 1} onClick={() => reorder(b.id, 1)}><ArrowDown size={13} /></Action></div>)}</div><Action className="pw-full" onClick={() => setLibrary(true)}><Plus size={16} />Add component</Action><div className="pw-editor-hint"><Sparkles size={17} /><p>Start with a section. Make it yours with content, images and your brand colors.</p></div></>}
      {tab === 'pages' && <><div className="pw-panel-title"><strong>Website pages</strong><p>Pages also appear in the website menu.</p></div>{site.draft.pages.map(p => <button type="button" key={p.id} className="pw-page-choice" aria-pressed={page.id === p.id} onClick={() => { setPageId(p.id); setSelectedId(''); }}><FileText size={16} />{p.title}<span>/{p.slug}</span></button>)}<Link className="pw-button pw-full" to={websiteHref('pages', site.id)}><Plus size={16} />Manage pages & blog</Link></>}
      {tab === 'chat' && <div className="pw-ai-panel"><div className="pw-ai-symbol"><Sparkles size={24} /></div><h2>Your creative partner</h2><p>Tell AI what you’d like to change. Review the suggestion before applying it.</p><Pill>AI simulation</Pill><form onSubmit={async e => { e.preventDefault(); setAiBusy(true); await new Promise(resolve => setTimeout(resolve, 700)); setAiSuggestion(`${site.draft.name}: ${prompt.trim().slice(0, 95)}`); setAiBusy(false); }}><Field label="Describe your change"><textarea required value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="A warmer, more welcoming headline…" /></Field><Action primary type="submit" disabled={aiBusy || !prompt.trim()}><Sparkles size={16} />{aiBusy ? 'Preparing suggestion…' : 'Generate suggestion'}</Action></form>{aiSuggestion && <div className="pw-ai-result"><strong>Suggested hero headline</strong><p>{aiSuggestion}</p><Action onClick={() => { change(d => { const hero = d.pages.find(p => p.id === page.id)?.blocks.find(b => b.kind === 'hero'); if (hero) hero.title = aiSuggestion; return d; }); setAiSuggestion(''); toast.success('Suggestion applied to the hero.'); }} disabled={!page.blocks.some(b => b.kind === 'hero')}>Apply to hero</Action><Action onClick={() => setAiSuggestion('')}>Dismiss</Action></div>}</div>}
    </EditorSidebar>
    <div className={`pw-canvas pw-device-${device}`}><div className="pw-canvas-label"><span>{site.draft.name} / {page.title}</span><Pill>Draft preview</Pill></div><div className="pw-canvas-frame"><StorefrontPreview key={`${site.id}-${page.id}`} content={site.draft} pageId={page.id} selectedBlock={selectedId} onSelect={setSelectedId} /></div><p className="pw-canvas-footnote">Click a section to edit · Changes are saved locally</p></div>
    <aside className="pw-inspector"><div className="pw-tabs">{[{ id: 'content', label: 'Content', icon: Layers }, { id: 'global', label: 'Global', icon: Palette }, { id: 'menu', label: 'Menu', icon: Menu }].map(({ id, label, icon: Icon }) => <button key={id} type="button" aria-pressed={settingsTab === id} onClick={() => setSettingsTab(id)}><Icon size={15} />{label}</button>)}</div><div className="pw-inspector-body">
      {settingsTab === 'content' && (block ? <><div className="pw-panel-title"><strong>{block.kind} settings</strong><p>Edit the selected section.</p></div><Field label="Heading"><input value={block.title} onChange={e => editBlock({ title: e.target.value })} /></Field><Field label="Description"><textarea rows={4} value={block.text} onChange={e => editBlock({ text: e.target.value })} /></Field>{block.kind === 'hero' && <Field label="Button text"><input value={block.button} onChange={e => editBlock({ button: e.target.value })} /></Field>}{['hero', 'image-text'].includes(block.kind) && <Field label="Section image"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => void upload(e.target.files?.[0], 'image').catch(() => toast.error('Unable to read image.'))} /></Field>}{['hero', 'image-text'].includes(block.kind) && <Action onClick={() => setMediaOpen(true)}><Image size={16} />Choose from media library</Action>}{block.kind === 'products' && <div className="pw-callout"><strong>Connected to Main</strong><p>Product details, prices and stock are owned by Main.</p><Link to={websiteHref('storefront', site.id)}>Choose products →</Link></div>}<label className="pw-check"><input type="checkbox" checked={block.visible} onChange={e => editBlock({ visible: e.target.checked })} />Show section</label><Action className="pw-danger" onClick={() => { change(d => ({ ...d, pages: d.pages.map(p => p.id === page.id ? { ...p, blocks: p.blocks.filter(b => b.id !== selectedId) } : p) })); setSelectedId(''); }}><Trash2 size={15} />Remove section</Action></> : <div className="pw-empty"><Layers size={26} /><h3>Select a section</h3><p>Choose a component on the canvas to edit its content.</p></div>)}
      {settingsTab === 'global' && <><div className="pw-panel-title"><strong>Global appearance</strong><p>Shared across every page.</p></div><Field label="Website name"><input value={site.draft.name} onChange={e => change(d => ({ ...d, name: e.target.value }))} /></Field><Field label="Brand color"><input type="color" value={site.draft.color} onChange={e => change(d => ({ ...d, color: e.target.value }))} /></Field><Field label="Typography"><select value={site.draft.font} onChange={e => change(d => ({ ...d, font: e.target.value }))}><option>Inter</option><option>Serif</option></select></Field><Field label="Logo"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void upload(e.target.files?.[0], 'logo').catch(() => toast.error('Unable to read image.'))} /></Field><Field label="Favicon"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void upload(e.target.files?.[0], 'favicon').catch(() => toast.error('Unable to read image.'))} /></Field><Field label="Language"><select value={site.draft.locale} onChange={e => change(d => ({ ...d, locale: e.target.value }))}><option value="en">English</option><option value="vi">Tiếng Việt</option><option value="ms">Bahasa Melayu</option></select></Field><p className="pw-muted">Language preference only. Automatic translation is not connected in this prototype.</p></>}
      {settingsTab === 'menu' && <><div className="pw-panel-title"><strong>Navigation</strong><p>Rename and reorder the links in your header.</p></div>{site.draft.pages.map((p, i) => <div key={p.id} className="pw-menu-item"><Field label={`Menu item ${i + 1}`}><input value={p.title} onChange={e => change(d => ({ ...d, pages: d.pages.map(page => page.id === p.id ? { ...page, title: e.target.value } : page) }))} /></Field><Action aria-label={`Move ${p.title} up`} disabled={i === 0} onClick={() => change(d => { [d.pages[i - 1], d.pages[i]] = [d.pages[i], d.pages[i - 1]]; return d; })}><ArrowUp size={15} /></Action></div>)}</>}
    </div></aside></div>
    <Modal open={mediaOpen} onClose={() => setMediaOpen(false)} title="Media library" description="Reuse images from your website and the Main product catalog."><div className="pw-media-grid">{media.map((src, i) => <button type="button" key={src} aria-label={`Use media image ${i + 1}`} onClick={() => { editBlock({ image: src }); setMediaOpen(false); }}><img src={src} alt={`Catalog image ${i + 1}`} loading="lazy" /></button>)}</div>{!media.length && <p>No images yet. Upload an image from the section settings.</p>}</Modal>
    <Modal open={library} onClose={() => setLibrary(false)} title="Add a component" description="Reusable sections from the PrimeWeb builder."><div className="pw-library">{(['announcement', 'hero', 'products', 'image-text', 'contact', 'footer'] as BlockKind[]).map(kind => <button type="button" key={kind} onClick={() => { const newBlock = makeBlock(kind); change(d => { d.pages.find(p => p.id === page.id)!.blocks.push(newBlock); return d; }); setSelectedId(newBlock.id); setLibrary(false); }}><Layers size={24} /><strong>{kind}</strong><span>Add to {page.title}</span></button>)}</div></Modal>
  </div>;
}
