import { useState, type CSSProperties } from 'react';
import { ArrowRight, ShoppingBag, Package, X, CheckCircle2 } from 'lucide-react';
import { getProducts, type Product } from '@/lib/product-store';
import type { WebsiteContent, Block } from './store';
import { Action } from './ui';

function ProductPhoto({ product }: { product: Product }) { return <div className="pw-product-photo">{product.images?.[0] ? <img src={product.images[0]} alt={product.name} loading="lazy" onError={e => { e.currentTarget.style.visibility = 'hidden'; }} /> : <Package size={42} />}</div>; }
export function StorefrontPreview({ content, selectedBlock, onSelect, pageId, interactive = false }: { content: WebsiteContent; selectedBlock?: string; onSelect?: (id: string) => void; pageId?: string; interactive?: boolean }) {
  const [page, setPage] = useState(pageId ?? content.pages[0].id);
  const [product, setProduct] = useState<Product | null>(null);
  const [cart, setCart] = useState<Product[]>([]);
  const [checkout, setCheckout] = useState(false);
  const [complete, setComplete] = useState(false);
  const [contactSent, setContactSent] = useState(false);
  const [blog, setBlog] = useState(false);
  const catalog = getProducts();
  const products = content.productIds.map(id => catalog.find(p => p.id === id)).filter((p): p is Product => !!p);
  const activePage = content.pages.find(p => p.id === (pageId ?? page)) ?? content.pages[0];
  const currencies = [...new Set(cart.map(p => p.price_currency || 'USD'))];
  function blockBody(block: Block) {
    switch (block.kind) {
      case 'announcement': return <div className="pw-store-announcement">{block.title}</div>;
      case 'hero': return <div className="pw-store-hero"><div><span className="pw-store-eyebrow">THE EVERYDAY COLLECTION</span><h2>{block.title}</h2><p>{block.text}</p><button type="button" onClick={() => interactive && document.getElementById('pw-products')?.scrollIntoView({ behavior: 'smooth', block: 'center' })}>{block.button}<ArrowRight size={16} /></button></div><div className="pw-store-hero-art">{block.image ? <img src={block.image} alt={block.title} /> : products[0]?.images?.[0] ? <img src={products[0].images[0]} alt={products[0].name} /> : <Package size={100} strokeWidth={0.7} />}<span>CURATED WITH CARE / 2026</span></div></div>;
      case 'products': return <div className="pw-store-section" id="pw-products"><span className="pw-store-eyebrow">{content.collection}</span><h2>{block.title}</h2><div className="pw-store-products">{products.map(p => <button key={p.id} type="button" className="pw-store-product" onClick={() => interactive && setProduct(p)}><ProductPhoto product={p} /><strong>{p.name}</strong><span>{p.price_currency} {p.retail_price.toLocaleString()}</span></button>)}</div>{!products.length && <p>Select products from Main in Storefront to build this collection.</p>}</div>;
      case 'image-text': return <div className="pw-store-story"><div>{block.image ? <img src={block.image} alt={block.title} /> : <div className="pw-store-monogram">{content.name.slice(0, 1)}</div>}</div><div><span className="pw-store-eyebrow">OUR STORY</span><h2>{block.title}</h2><p>{block.text}</p></div></div>;
      case 'contact': return <div className="pw-store-section"><h2>{block.title}</h2><p>{block.text}</p>{contactSent ? <p role="status">Thank you. Your message was received in this demo.</p> : <form className="pw-contact-form" onSubmit={e => { e.preventDefault(); setContactSent(true); }}><label>Your email<input type="email" required placeholder="you@example.com" disabled={!interactive} /></label><label>Your message<textarea required placeholder="How can we help?" disabled={!interactive} /></label><button disabled={!interactive}>Send message</button></form>}</div>;
      case 'footer': return <footer className="pw-store-footer"><strong>{content.name}</strong><p>{block.title}</p><span>{content.email} · {content.locale.toUpperCase()}</span></footer>;
    }
  }
  return <div className="pw-store" style={{ '--site-color': content.color, fontFamily: content.font === 'Serif' ? 'Georgia, serif' : 'Inter, sans-serif' } as CSSProperties}>
    <nav className="pw-store-nav" aria-label="Website navigation"><strong>{content.logo ? <img src={content.logo} alt={content.name} /> : content.name}</strong><div>{content.pages.map(p => <button key={p.id} type="button" onClick={() => { if (interactive) { setPage(p.id); setBlog(false); } }}>{p.title}</button>)}{content.posts.some(p => p.status === 'published') && <button type="button" onClick={() => interactive && setBlog(true)}>Journal</button>}</div><button type="button" aria-label={`Shopping bag (${cart.length})`} onClick={() => interactive && setCheckout(true)}><ShoppingBag size={18} />{cart.length > 0 && cart.length}</button></nav>
    {blog ? <section className="pw-store-section"><h2>Journal</h2>{content.posts.filter(p => p.status === 'published').map(p => <article key={p.id}><span className="pw-store-eyebrow">{p.category}</span><h3>{p.title}</h3><p>{p.content}</p></article>)}</section> : activePage.blocks.filter(b => b.visible).map(block => <section key={block.id} tabIndex={onSelect ? 0 : undefined} aria-label={onSelect ? `Select ${block.kind} section` : undefined} onKeyDown={e => { if (e.target === e.currentTarget && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); onSelect?.(block.id); } }} onClick={() => onSelect?.(block.id)} className={onSelect ? `pw-selectable ${selectedBlock === block.id ? 'is-selected' : ''}` : ''}>{blockBody(block)}</section>)}
    {product && <div className="pw-store-overlay"><Action aria-label="Close product" onClick={() => setProduct(null)}><X size={18} /></Action><ProductPhoto product={product} /><h2>{product.name}</h2><p>{product.description || 'Selected from the Main product catalog.'}</p><strong>{product.price_currency} {product.retail_price.toLocaleString()}</strong><Action primary onClick={() => { setCart([...cart, product]); setProduct(null); }}>Add to bag</Action></div>}
    {checkout && <div className="pw-store-overlay"><Action aria-label="Close checkout" onClick={() => { setCheckout(false); setComplete(false); }}><X size={18} /></Action>{complete ? <><CheckCircle2 size={40} /><h2>Demo order confirmed</h2><p>No payment was collected and no real order was created.</p><Action onClick={() => { setCheckout(false); setComplete(false); }}>Continue shopping</Action></> : <><h2>Your bag</h2>{cart.map((p, index) => <div className="pw-row" key={`${p.id}-${index}`}><span>{p.name}</span><span>{p.price_currency} {p.retail_price.toLocaleString()}</span><Action aria-label={`Remove ${p.name}`} onClick={() => setCart(cart.filter((_, i) => i !== index))}><X size={15} /></Action></div>)}{!cart.length ? <p>Your bag is empty.</p> : <><p>{currencies.map(currency => `${currency} ${cart.filter(p => (p.price_currency || 'USD') === currency).reduce((sum, p) => sum + p.retail_price, 0).toLocaleString()}`).join(' + ')}</p><form className="pw-contact-form" onSubmit={e => { e.preventDefault(); setComplete(true); setCart([]); }}><label>Email<input type="email" required /></label><label>Delivery address<input required /></label><label>Payment method<select><option>Cash on delivery · demo</option><option>Card · demo, no charge</option></select></label><p>Checkout preview · shipping and payment settings are managed in Main.</p><button>Place demo order</button></form></>}</>}</div>}
  </div>;
}
