import { expect, test } from '@playwright/test';
import { installPrimeSession } from './helpers/prime-session';
test.beforeEach(async ({ page }) => { await installPrimeSession(page); await page.goto('/builder/sites'); await expect(page.getByRole('heading', { name: 'My websites', exact: true })).toBeVisible(); });

test('create, edit, undo, reload and publish a separate snapshot', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('button', { name: 'Create website', exact: true }).click();
  await page.getByLabel('Website name', { exact: true }).fill('Seller Demo');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.locator('.pw-picker-list input').first().check();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Create website', exact: true }).click();
  await expect(page.getByLabel('Selected website')).toContainText('Seller Demo');
  await page.getByLabel('Heading', { exact: true }).fill('A new story');
  await expect(page.locator('.pw-canvas h2').first()).toHaveText('A new story');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.locator('.pw-canvas h2').first()).toHaveText('Good things. Everyday.');
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.reload();
  await expect(page.locator('.pw-canvas h2').first()).toHaveText('A new story');
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Publish demo website', exact: true }).click();
  await expect(page).toHaveURL(/version=live/);
  await expect(page.locator('.pw-store h2').first()).toHaveText('A new story');
  await page.getByRole('link', { name: 'Back to editor' }).click();
  await page.getByLabel('Heading', { exact: true }).fill('Still a draft');
  const id = new URL(page.url()).searchParams.get('site');
  await page.goto(`/builder/preview?site=${id}&version=live`);
  await expect(page.locator('.pw-store h2').first()).toHaveText('A new story');
  await page.getByRole('link', { name: 'View draft', exact: true }).click();
  await expect(page.locator('.pw-store h2').first()).toHaveText('Still a draft');
  expect(errors).toEqual([]);
});

test('isolates websites, validates domain and persists blog', async ({ page }) => {
  await page.goto('/builder/pages?site=everyday');
  await page.getByRole('button', { name: 'Add page', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Contact');
  await page.getByLabel('Page URL').fill('contact');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('.pw-table-row').filter({ hasText: 'Contact' })).toBeVisible();
  await page.getByLabel('Selected website').selectOption('studio');
  await expect(page.locator('.pw-table-row').filter({ hasText: 'Contact' })).toHaveCount(0);
  await page.goto('/builder/domains?site=everyday');
  await page.getByLabel('Custom domain').fill('https://invalid/path');
  await page.getByRole('button', { name: 'Save domain', exact: true }).click();
  await expect(page.locator('.pw-error')).toContainText('Enter a domain');
  await page.getByLabel('Custom domain').fill('shop.example.com');
  await page.getByRole('button', { name: 'Save domain', exact: true }).click();
  await page.getByRole('button', { name: 'Simulate verification' }).click();
  await expect(page.getByText('Verified · simulated', { exact: true })).toBeVisible();
  await page.goto('/builder/pages?site=everyday');
  await page.getByRole('button', { name: 'Blog posts', exact: true }).click();
  await page.getByRole('button', { name: 'Write a post', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Our new collection');
  await page.getByLabel('Content', { exact: true }).fill('Carefully chosen essentials.');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Blog posts', exact: true }).click();
  await expect(page.getByText('Our new collection', { exact: true })).toBeVisible();
});

test('product details and demo checkout', async ({ page }) => {
  await page.goto('/builder/preview?site=everyday');
  await page.locator('.pw-store-product').first().click();
  await page.getByRole('button', { name: 'Add to bag', exact: true }).click();
  await page.getByRole('button', { name: 'Shopping bag (1)' }).click();
  await page.getByLabel('Email', { exact: true }).fill('demo@example.com');
  await page.getByLabel('Delivery address').fill('123 Demo Street');
  await page.getByRole('button', { name: 'Place demo order', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Demo order confirmed' })).toBeVisible();
});

test('desktop, dark editor and mobile layout', async ({ page }) => {
  await page.screenshot({ path: '/private/tmp/primeweb-sites-light.png', fullPage: true });
  await page.goto('/builder/theme?site=everyday');
  await expect(page.getByLabel('Heading', { exact: true })).toBeVisible();
  await page.screenshot({ path: '/private/tmp/primeweb-editor-light.png', fullPage: true });
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.waitForTimeout(400);
  await expect(page.locator('.pw-primary').first()).toHaveCSS('background-color', 'rgb(45, 212, 191)');
  await page.screenshot({ path: '/private/tmp/primeweb-editor-dark.png', fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/builder/sites');
  await expect(page.getByRole('button', { name: 'Create website', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/private/tmp/primeweb-sites-mobile.png', fullPage: true });
  await page.goto('/builder/theme?site=everyday');
  await page.getByRole('button', { name: 'mobile preview', exact: true }).click();
  await page.getByLabel('Heading', { exact: true }).fill('Made for mobile');
  await expect(page.locator('.pw-canvas h2').first()).toHaveText('Made for mobile');
  expect(await page.locator('#main-content').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: '/private/tmp/primeweb-editor-mobile.png', fullPage: true });
});

test('AI failure can retry, media can be reused, and reset restores examples', async ({ page }) => {
  await page.getByRole('button', { name: 'Create website', exact: true }).click();
  await page.getByLabel('Website name', { exact: true }).fill('AI Example');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Create with AI', exact: true }).click();
  await page.getByLabel('Describe your website').fill('A welcoming store for everyday objects.');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Demo: simulate a generation failure').check();
  await page.getByRole('button', { name: 'Create website', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Demo generation failed');
  await page.getByLabel('Demo: simulate a generation failure').uncheck();
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect(page.locator('.pw-canvas')).toContainText('A welcoming store for everyday objects.');
  await page.getByRole('button', { name: 'Choose from media library', exact: true }).click();
  await page.getByRole('button', { name: 'Use media image 1', exact: true }).click();
  await expect(page.locator('.pw-store-hero-art img')).toBeVisible();
  await page.getByRole('button', { name: 'AI Chat', exact: true }).click();
  await page.getByLabel('Describe your change').fill('Made for a slower Sunday');
  await page.getByRole('button', { name: 'Generate suggestion', exact: true }).click();
  await page.getByRole('button', { name: 'Apply to hero', exact: true }).click();
  await expect(page.locator('.pw-canvas h2').first()).toContainText('Made for a slower Sunday');
  await page.getByRole('button', { name: 'Reset PrimeWeb demo', exact: true }).click();
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  await expect(page.locator('.pw-site-card')).toHaveCount(3);
  await expect(page.getByRole('heading', { name: 'AI Example', exact: true })).toHaveCount(0);
});
