import { useState, type FormEvent } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { ordersApi, orderMoney, type ManualOrderInput, type OrderRecord } from '@/lib/orders-api';

const fieldClass = 'h-10 w-full rounded-md border border-input bg-background px-3 text-sm';
export function OrderField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>; }
export function ManualOrderDialog({ onClose, onCreated, warehouses, initialOrder }: { onClose: () => void; onCreated: (order: OrderRecord) => void; warehouses: string[]; initialOrder?: OrderRecord }) {
  const [form, setForm] = useState<ManualOrderInput>(() => ({ orderKey: `MAN-${Date.now()}`, requestKey: crypto.randomUUID(), canonicalStatus: 'created', currencyCode: 'VND', buyerSnapshot: { name: '', phone: '', email: '' }, shippingAddressSnapshot: { address: '', city: '', country: 'VN', postalCode: '' }, lines: [{ sku: '', name: '', quantity: 1, unitPrice: 0 }], totals: { discount: 0, shipping: 0, tax: 0 }, payment: { state: 'Unpaid', method: 'COD', reference: '' }, metadata: { handlingType: 'self', store: 'Manual', warehouse: 'Unassigned', assignee: 'Unassigned', notes: '', tags: '' } }));
  const [initialized, setInitialized] = useState(false);
  if (initialOrder && !initialized) {
    setForm({ ...initialOrder, canonicalStatus: 'draft', totals: { discount: initialOrder.totals.discount || 0, shipping: initialOrder.totals.shipping || 0, tax: initialOrder.totals.tax || 0 }, metadata: { ...initialOrder.metadata, tags: initialOrder.metadata.tags.join(', ') } });
    setInitialized(true);
  }
  const [pending, setPending] = useState(false); const [error, setError] = useState(''); const [dirty, setDirty] = useState(false);
  const subtotal = form.lines.reduce((sum, l) => sum + l.quantity * l.unitPrice, 0);
  const total = subtotal - form.totals.discount + form.totals.shipping + form.totals.tax;
  function close() { if (!pending && (!dirty || window.confirm('Discard this unsaved order?'))) onClose(); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return;
    const status = (event.nativeEvent as SubmitEvent).submitter?.getAttribute('value') === 'draft' ? 'draft' : 'created';
    setPending(true); setError('');
    try { const payload: ManualOrderInput = { ...form, canonicalStatus: status }; const response = initialOrder ? await ordersApi.command(initialOrder, { action: 'edit-draft', order: payload }) : await ordersApi.create(payload); onCreated(response.data); }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to create order.'); }
    finally { setPending(false); }
  }
  return <Sheet open onOpenChange={(open) => !open && close()}><SheetContent className="flex w-full flex-col sm:max-w-3xl p-0"><SheetHeader className="border-b p-5"><SheetTitle>{initialOrder ? 'Edit draft order' : 'Create manual order'}</SheetTitle><SheetDescription>Add a customer, delivery address and order items. Inventory is reserved during fulfillment.</SheetDescription></SheetHeader>
    <form onSubmit={submit} onChange={() => setDirty(true)} className="flex min-h-0 flex-1 flex-col">
      <fieldset disabled={pending} className="min-h-0 flex-1 space-y-6 overflow-y-auto p-5">
        <section className="grid gap-4 sm:grid-cols-3"><OrderField label="Order reference"><Input required maxLength={220} value={form.orderKey} onChange={(e) => setForm({ ...form, orderKey: e.target.value })} /></OrderField><OrderField label="Sales channel / Store"><Input required value={form.metadata.store} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, store: e.target.value } })} /></OrderField><OrderField label="Currency"><select className={fieldClass} value={form.currencyCode} onChange={(e) => setForm({ ...form, currencyCode: e.target.value })}>{['VND', 'USD', 'JPY', 'SGD', 'MYR'].map((c) => <option key={c}>{c}</option>)}</select></OrderField></section>
        <section><h3 className="mb-3 font-semibold">Customer</h3><div className="grid gap-4 sm:grid-cols-3">{(['name', 'phone', 'email'] as const).map((key) => <OrderField key={key} label={{ name: 'Customer name', phone: 'Phone number', email: 'Email (optional)' }[key]}><Input required={key !== 'email'} type={key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'} value={form.buyerSnapshot[key]} onChange={(e) => setForm({ ...form, buyerSnapshot: { ...form.buyerSnapshot, [key]: e.target.value } })} /></OrderField>)}</div></section>
        <section><h3 className="mb-3 font-semibold">Delivery address</h3><div className="grid gap-4 sm:grid-cols-2">{(['address', 'city', 'country', 'postalCode'] as const).map((key) => <OrderField key={key} label={{ address: 'Street address', city: 'City / Province', country: 'Country', postalCode: 'Postal code (optional)' }[key]}><Input required={key !== 'postalCode'} value={form.shippingAddressSnapshot[key]} onChange={(e) => setForm({ ...form, shippingAddressSnapshot: { ...form.shippingAddressSnapshot, [key]: e.target.value } })} /></OrderField>)}</div></section>
        <section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Order items</h3><Button type="button" variant="outline" disabled={form.lines.length >= 100} onClick={() => { setDirty(true); setForm({ ...form, lines: [...form.lines, { sku: '', name: '', quantity: 1, unitPrice: 0 }] }); }}><Plus className="size-4" />Add item</Button></div>
          <div className="space-y-3">{form.lines.map((line, index) => <div key={index} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-2"><OrderField label={`Item ${index + 1} SKU`}><Input required value={line.sku} onChange={(e) => setForm({ ...form, lines: form.lines.map((l, i) => i === index ? { ...l, sku: e.target.value } : l) })} /></OrderField><OrderField label={`Item ${index + 1} name`}><Input required value={line.name} onChange={(e) => setForm({ ...form, lines: form.lines.map((l, i) => i === index ? { ...l, name: e.target.value } : l) })} /></OrderField><div className="grid grid-cols-2 gap-3"><OrderField label={`Item ${index + 1} quantity`}><Input type="number" required min={1} max={100000} step={1} value={line.quantity} onChange={(e) => setForm({ ...form, lines: form.lines.map((l, i) => i === index ? { ...l, quantity: Number(e.target.value) } : l) })} /></OrderField><OrderField label={`Item ${index + 1} unit price`}><Input type="number" required min={0} step={['VND', 'JPY'].includes(form.currencyCode) ? 1 : 0.01} value={line.unitPrice} onChange={(e) => setForm({ ...form, lines: form.lines.map((l, i) => i === index ? { ...l, unitPrice: Number(e.target.value) } : l) })} /></OrderField></div><div className="flex items-end justify-between"><span className="pb-2 tabular-nums">{orderMoney(line.quantity * line.unitPrice, form.currencyCode)}</span><Button type="button" variant="ghost" disabled={form.lines.length === 1} aria-label={`Remove item ${index + 1}`} onClick={() => { setDirty(true); setForm({ ...form, lines: form.lines.filter((_, i) => i !== index) }); }}><Trash2 className="size-4" /></Button></div></div>)}</div>
        </section>
        <section className="grid gap-4 sm:grid-cols-3">{(['discount', 'shipping', 'tax'] as const).map((key) => <OrderField key={key} label={{ discount: 'Discount', shipping: 'Shipping fee', tax: 'Tax' }[key]}><Input type="number" min={0} max={key === 'discount' ? subtotal : undefined} step={['VND', 'JPY'].includes(form.currencyCode) ? 1 : 0.01} value={form.totals[key]} onChange={(e) => setForm({ ...form, totals: { ...form.totals, [key]: Number(e.target.value) } })} /></OrderField>)}</section>
        <section className="grid gap-4 sm:grid-cols-2"><OrderField label="Payment method"><select className={fieldClass} value={form.payment.method} onChange={(e) => setForm({ ...form, payment: { ...form.payment, method: e.target.value } })}>{['COD', 'Bank transfer', 'Cash', 'Card'].map((c) => <option key={c}>{c}</option>)}</select></OrderField><OrderField label="Payment status"><select className={fieldClass} value={form.payment.state} onChange={(e) => setForm({ ...form, payment: { ...form.payment, state: e.target.value } })}><option>Unpaid</option><option>Paid</option></select></OrderField>{form.payment.state === 'Paid' && <OrderField label="Payment evidence / Reference"><Input required value={form.payment.reference} onChange={(e) => setForm({ ...form, payment: { ...form.payment, reference: e.target.value } })} /></OrderField>}<OrderField label="Fulfillment type"><select className={fieldClass} required value={form.metadata.handlingType || ''} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, handlingType: e.target.value as 'self' | 'marketplace' } })}><option value="" disabled>Select fulfillment type</option><option value="self">Seller fulfilled</option><option value="marketplace">Marketplace fulfilled</option></select></OrderField><OrderField label="Preferred warehouse"><select className={fieldClass} value={form.metadata.warehouse} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, warehouse: e.target.value } })}>{['Unassigned', ...warehouses.filter((w) => w !== 'Unassigned')].map((w) => <option key={w}>{w}</option>)}</select></OrderField><OrderField label="Assigned to"><Input value={form.metadata.assignee} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, assignee: e.target.value } })} /></OrderField><OrderField label="Customer tags (comma separated)"><Input value={form.metadata.tags} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, tags: e.target.value } })} /></OrderField><OrderField label="Order notes"><Input value={form.metadata.notes} onChange={(e) => setForm({ ...form, metadata: { ...form.metadata, notes: e.target.value } })} /></OrderField></section>
      </fieldset>
      <div className="shrink-0 space-y-3 border-t bg-background p-4">{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap items-center gap-2"><div className="mr-auto"><div className="text-xs text-muted-foreground">Order total</div><output className="font-semibold tabular-nums">{orderMoney(total, form.currencyCode)}</output></div><Button type="button" variant="ghost" disabled={pending} onClick={close}>Cancel</Button><Button type="submit" name="status" value="draft" variant="outline" disabled={pending}>Save draft</Button><Button type="submit" name="status" value="created" disabled={pending}>{pending ? 'Saving…' : 'Create order'}</Button></div></div>
    </form>
  </SheetContent></Sheet>;
}
