export const legacyOrderExamples = [
  { id: 'PRM-240812-1048', date: 'Aug 12 · 10:48', customer: 'Nguyen Minh Anh', tags: ['VIP'], store: 'PrimeWeb', owner: 'Online Store', warehouse: 'HCM Central Warehouse', total: '₫1,284,000', payment: 'Paid', status: 'Pending Confirmation', sla: '12m remaining', slaRisk: true, assignee: 'Linh Nguyen', reservation: 'Reserved', carrier: 'GHN', tracking: 'GHN-8821048', needsPaymentVerification: false, syncError: false, readyForPickup: false, pickupOverdue: false },
  { id: 'POS-240812-0931', date: 'Aug 12 · 09:31', customer: 'Tran Quoc Huy', tags: [], store: 'PrimePOS', owner: 'Cashier: Mai Linh', warehouse: 'District 1 Branch', total: '₫688,000', payment: 'Paid', status: 'Completed', sla: 'On time', slaRisk: false, assignee: 'Mai Linh', reservation: 'Released', carrier: 'Store pickup', tracking: '—', needsPaymentVerification: false, syncError: false, readyForPickup: false, pickupOverdue: false },
  { id: 'SHP-240812-0816', date: 'Aug 12 · 08:16', customer: 'Le Hoang Yen', tags: ['High Return Risk'], store: 'Shopee', owner: 'Shopee Flagship', warehouse: 'Binh Duong Warehouse', total: '₫942,000', payment: 'Unpaid', status: 'Pending Confirmation', sla: 'Breached by 34m', slaRisk: true, assignee: 'Unassigned', reservation: 'Allocation failed', carrier: 'GHTK', tracking: 'Pending', needsPaymentVerification: true, syncError: false, readyForPickup: false, pickupOverdue: false },
  { id: 'CRM-240811-1742', date: 'Aug 11 · 17:42', customer: 'An Phat Company', tags: ['B2B'], store: 'PrimeCRM', owner: 'Sales Rep: Hoang Nam', warehouse: 'HCM Central Warehouse', total: '₫8,460,000', payment: 'Paid', status: 'Awaiting Shipment', sla: 'Pickup overdue by 22m', slaRisk: false, assignee: 'Hoang Nam', reservation: 'Reserved', carrier: 'ViettelPost', tracking: 'VTP-617420', needsPaymentVerification: false, syncError: false, readyForPickup: true, pickupOverdue: true },
  { id: 'TTK-240811-1620', date: 'Aug 11 · 16:20', customer: 'Pham Ngoc Ha', tags: [], store: 'TikTok Shop', owner: 'TikTok Official', warehouse: 'Hanoi Warehouse', total: '₫1,120,000', payment: 'Paid', status: 'In Transit', sla: 'On time', slaRisk: false, assignee: 'Thu Tran', reservation: 'Dispatched', carrier: 'GHN', tracking: 'GHN-811620', needsPaymentVerification: false, syncError: true, readyForPickup: false, pickupOverdue: false },
  { id: 'LZD-240811-1515', date: 'Aug 11 · 15:15', customer: 'Doan Thu Trang', tags: ['VIP'], store: 'Lazada', owner: 'Lazada Flagship', warehouse: 'HCM Central Warehouse', total: '₫2,340,000', payment: 'Refunded', status: 'Returned', sla: 'Return received', slaRisk: false, assignee: 'Linh Nguyen', reservation: 'Released', carrier: 'LEX', tracking: 'LZD-RETURN-1515', needsPaymentVerification: false, syncError: false, readyForPickup: false, pickupOverdue: false },
  { id: 'PRM-240811-1442', date: 'Aug 11 · 14:42', customer: 'Vo Gia Bao', tags: [], store: 'PrimeWeb', owner: 'Online Store', warehouse: 'Hanoi Warehouse', total: '₫756,000', payment: 'Paid', status: 'Awaiting Shipment', sla: '24m remaining', slaRisk: true, assignee: 'Linh Nguyen', reservation: 'Allocation failed', carrier: 'GHN', tracking: 'Pending', needsPaymentVerification: false, syncError: false, readyForPickup: false, pickupOverdue: false },
  { id: 'SHP-240811-1328', date: 'Aug 11 · 13:28', customer: 'Pham Bao Chau', tags: ['B2B'], store: 'Shopee', owner: 'Shopee Flagship', warehouse: 'Binh Duong Warehouse', total: '₫3,180,000', payment: 'Unpaid', status: 'Pending Confirmation', sla: '42m remaining', slaRisk: false, assignee: 'Finance Team', reservation: 'Allocation failed', carrier: 'SPX Express', tracking: 'Pending', needsPaymentVerification: true, syncError: true, readyForPickup: false, pickupOverdue: false },
];
