// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { readyMasterFields } from '@/test/fixtures/listing-master';
import { editListingSection, applyListingSection, completeListingDetails } from '@/test/fixtures/complete-listing-details';
import { ProductListingIntake } from './ProductListingIntake';
import { createEmptyListingCatalog } from '@/lib/listing-intake-catalog';
import { getCatalogImportItems, saveCatalogImportItems, type CatalogImportItem } from '@/lib/catalog-import-store';
import { commitListingReviewProducts } from '@/lib/product-store';
import { addProduct, deleteProduct, getProductById, getProducts, type Product } from '@/lib/product-store';
vi.mock('@/hooks/use-toast', () => ({ useToast: () => ({ toast: vi.fn() }) }));
let original: CatalogImportItem[];
let ids: Set<string>;
let legacyFixtures: ReturnType<typeof getProducts>;
beforeEach(() => {
  localStorage.removeItem('prime-listing-review-guide-dismissed-v1');
  // This suite covers the new-listing inbox; existing-link migration has its own integration suite.
  legacyFixtures = structuredClone(getProducts().filter(product => product.import_result === 'needs_review'));
  commitListingReviewProducts(legacyFixtures.map(product => ({ ...product, import_result: undefined, import_issues: [] })));
  original = getCatalogImportItems({ requireConfirmation: true });
  ids = new Set(getProducts().map(product => product.id));
  const sample = original.find(item => item.variants === 1)!;
  saveCatalogImportItems(['a', 'b'].map((id, index) => ({ ...sample, images: readyMasterFields().images, description: readyMasterFields().description, id, listingId: `ui-intake-${id}`, title: 'Same product demo', channelSku: `UI-${id}`, storeName: `Shop ${index}`, suggestedProductId: undefined, resolvedProductId: undefined, confirmed: false, resolution: 'later', status: 'unmatched' })));
});
afterEach(() => {
  localStorage.removeItem('prime-listing-review-guide-dismissed-v1');
  commitListingReviewProducts(legacyFixtures);
  cleanup();
  getProducts().filter(product => !ids.has(product.id)).forEach(product => deleteProduct(product.id));
  saveCatalogImportItems(original);
});
describe('Listing review drawer', () => {
  it('shows creation instead of nonexistent suggestions in an isolated no-Masters catalog', () => {
    const catalog = createEmptyListingCatalog(getCatalogImportItems({ requireConfirmation: true }));
    const before = structuredClone(getProducts());
    render(<ProductListingIntake catalog={catalog} onChanged={vi.fn()} onOpenMaster={vi.fn()} stayInQueue />);
    expect(screen.queryByRole('columnheader', { name: 'Product Master' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Review suggestion' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Choose Master' })).not.toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', { name: 'Create Master' })[0]);
    editListingSection('Product essentials');
    expect(screen.getByRole('textbox', { name: /^Product name/ })).toHaveValue('Same product demo');
    expect(screen.queryByRole('button', { name: 'Use existing Master' })).not.toBeInTheDocument();

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(catalog.products()).toHaveLength(1);
    expect(screen.getByRole('button', { name: 'Review suggestion' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Review suggestion' }));
    expect(screen.getByText('Suggested Product Master')).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Link to this Master' }));
    expect(catalog.products()[0].channels).toHaveLength(2);
    expect(getProducts()).toEqual(before);
    expect(screen.queryByRole('button', { name: 'View updated Master' })).not.toBeInTheDocument();
  });
  it('requires an explicit grouping choice and reviews different products sequentially', () => {
    const sources = getCatalogImportItems({ requireConfirmation: true }).map((source, index) => ({ ...source, title: `Different product ${index}` }));
    const catalog = createEmptyListingCatalog(sources);
    const onChanged = vi.fn();
    render(<ProductListingIntake catalog={catalog} onChanged={onChanged} onOpenMaster={vi.fn()} stayInQueue />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    expect(screen.queryByRole('button', { name: 'Link to one Master' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Create one Master' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Review selected listings' }));
    expect(screen.getByRole('radio', { name: /Review separately/ })).toBeChecked();
    expect(catalog.products()).toEqual([]);
    fireEvent.click(screen.getByRole('button', { name: 'Review first listing' }));
    editListingSection('Product essentials');
    expect(screen.getByRole('textbox', { name: /^Product name/ })).toHaveValue('Different product 0');

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(catalog.products()).toHaveLength(1);
    editListingSection('Product essentials');
    expect(screen.getByRole('textbox', { name: /^Product name/ })).toHaveValue('Different product 1');

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(catalog.products()).toHaveLength(2);
    expect(catalog.products().every(product => product.channels.length === 1)).toBe(true);
    expect(onChanged).toHaveBeenCalledTimes(2);
  });
  it('creates one three-SKU Master for an explicitly grouped pair of variant listings', () => {
    const fixtures = original.filter(item => ['imp-002', 'imp-011'].includes(item.id)).map(item => ({ ...item, images: readyMasterFields().images }));
    const catalog = createEmptyListingCatalog(fixtures);
    render(<ProductListingIntake catalog={catalog} onChanged={vi.fn()} onOpenMaster={vi.fn()} stayInQueue />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    fireEvent.click(screen.getByRole('button', { name: 'Review selected listings' }));
    fireEvent.click(screen.getByRole('radio', { name: /Same product, one Master/ }));
    fireEvent.click(screen.getByRole('button', { name: 'Review one product' }));
    editListingSection('Product essentials');
    expect(screen.getByRole('radio', { name: 'With variants' })).toBeChecked();
    fireEvent.click(screen.getByRole('checkbox', { name: /I checked/ }));
    applyListingSection();
    editListingSection('Variants, pricing & SKU mapping');
    expect(screen.getAllByLabelText('Master variant SKU')).toHaveLength(3);
    expect(screen.getAllByRole('combobox', { name: /Master SKU for shop SKU/ })).toHaveLength(6);
    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(catalog.products()).toHaveLength(1);
    expect(catalog.products()[0].skus).toHaveLength(3);
    expect(catalog.products()[0].channels).toHaveLength(2);
  });
  it('keeps help optional and preserves the filtered selection without writing product or listing data', () => {
    const onChanged = vi.fn();
    const beforeProducts = structuredClone(getProducts());
    const beforeListings = structuredClone(getCatalogImportItems({ requireConfirmation: true }));
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={vi.fn()} stayInQueue />);
    expect(screen.getByRole('region', { name: 'Listing review guide' })).toBeVisible();
    fireEvent.change(screen.getByRole('textbox', { name: 'Search shop listings' }), { target: { value: 'Shop 0' } });
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select listing UI-a from Shop 0' }));
    fireEvent.click(screen.getByRole('button', { name: 'Got it' }));
    fireEvent.click(screen.getByRole('button', { name: 'How this works' }));
    expect(screen.getByRole('list', { name: 'Listing review steps' })).toBeVisible();
    expect(screen.getByRole('textbox', { name: 'Search shop listings' })).toHaveValue('Shop 0');
    expect(screen.getByRole('checkbox', { name: 'Select listing UI-a from Shop 0' })).toBeChecked();
    fireEvent.click(screen.getByRole('button', { name: 'Choose Master' }));
    expect(screen.queryByRole('region', { name: 'Listing review guide' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Back to listings' }));
    expect(screen.getByRole('button', { name: 'How this works' })).toHaveAttribute('aria-expanded', 'false');
    expect(onChanged).not.toHaveBeenCalled();
    expect(getProducts()).toEqual(beforeProducts);
    expect(getCatalogImportItems({ requireConfirmation: true })).toEqual(beforeListings);
  });
  it('returns from comparison to the same filtered listing queue without confirming or advancing', () => {
    const master = { ...getProducts()[0], ...readyMasterFields(), id: 'ui-back-master', name: 'Back navigation Master', sku_code: 'UI-BACK', brand: 'Master Brand', has_variants: false, product_type: 'single', skus: [], channels: [], import_sources: [], status: 'draft', import_result: undefined } as Product;
    addProduct(master);
    saveCatalogImportItems(getCatalogImportItems({ requireConfirmation: true }).map(item => ({ ...item, channelSku: master.sku_code, brand: 'Different Source Brand', suggestedProductId: master.id, status: 'conflict' })));
    const onChanged = vi.fn(); const onStageChange = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={vi.fn()} onStageChange={onStageChange} stayInQueue />);
    fireEvent.change(screen.getByRole('textbox', { name: 'Search shop listings' }), { target: { value: 'Shop 0' } });
    fireEvent.click(screen.getByRole('button', { name: 'Review suggestion' }));
    expect(screen.getByRole('group', { name: 'Differences to check' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Back to listings' }));
    expect(screen.getByRole('heading', { name: '2 listings to review' })).toBeVisible();
    expect(screen.getByRole('textbox', { name: 'Search shop listings' })).toHaveValue('Shop 0');
    expect(screen.getAllByRole('button', { name: 'Review suggestion' })).toHaveLength(1);
    expect(screen.getByRole('checkbox', { name: 'Select listing UI-BACK from Shop 0' })).toBeChecked();
    expect(screen.queryByRole('region', { name: 'Compare product details' })).not.toBeInTheDocument();
    expect(onStageChange).toHaveBeenLastCalledWith('queue');
    expect(onChanged).not.toHaveBeenCalled();
    expect(getProductById(master.id)?.channels).toEqual([]);
    expect(getCatalogImportItems({ requireConfirmation: true }).every(item => !item.confirmed)).toBe(true);
  });
  it('does not preselect a Master without a suggestion or save a decision when canceled', () => {
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={vi.fn()} />);
    fireEvent.click(screen.getAllByRole('button', { name: 'Choose Master' })[0]);
    const dialog = within(screen.getByRole('region', { name: 'Find a Product Master' }));
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    expect(dialog.queryByRole('button', { name: /Confirm link/ })).not.toBeInTheDocument();
    expect(dialog.getAllByRole('button', { name: /^Compare with/ }).length).toBeGreaterThan(0);
    fireEvent.click(dialog.getByRole('button', { name: 'Back to listings' }));
    expect(getProducts().length).toBe(ids.size);
    expect(getCatalogImportItems({ requireConfirmation: true }).some(item => item.confirmed)).toBe(false);
  });
  it('keeps direct link and create actions when Masters exist without an onboarding grouping step', () => {
    const beforeProducts = structuredClone(getProducts());
    const beforeListings = structuredClone(getCatalogImportItems({ requireConfirmation: true }));
    const onChanged = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={vi.fn()} stayInQueue />);
    expect(screen.getByRole('columnheader', { name: 'Product Master' })).toBeVisible();
    expect(screen.getAllByRole('button', { name: 'Choose Master' })).toHaveLength(2);
    expect(screen.queryByRole('button', { name: 'Create Master', exact: true })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select listing UI-a from Shop 0' }));
    expect(screen.getByRole('button', { name: 'Link to one Master' })).toBeEnabled();
    expect(screen.getByRole('button', { name: 'Create one Master' })).toBeEnabled();
    expect(screen.queryByRole('button', { name: 'Review selected listings' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select listing UI-b from Shop 1' }));
    fireEvent.click(screen.getByRole('button', { name: 'Link to one Master' }));
    expect(screen.getByRole('region', { name: 'Find a Product Master' })).toBeVisible();
    expect(screen.queryByRole('radio', { name: /Review separately/ })).not.toBeInTheDocument();
    expect(screen.getByRole('region', { name: 'Selected listings 2' })).toHaveTextContent('UI-a');
    expect(screen.getByRole('region', { name: 'Selected listings 2' })).toHaveTextContent('UI-b');
    fireEvent.click(screen.getByRole('button', { name: 'Back to listings' }));
    expect(screen.getByRole('checkbox', { name: 'Select listing UI-a from Shop 0' })).toBeChecked();
    expect(screen.getByRole('checkbox', { name: 'Select listing UI-b from Shop 1' })).toBeChecked();
    fireEvent.click(screen.getByRole('button', { name: 'Create one Master' }));
    expect(screen.getByRole('region', { name: 'Create one Master' })).toBeVisible();
    expect(screen.queryByRole('radio', { name: /Same product, one Master/ })).not.toBeInTheDocument();
    expect(onChanged).not.toHaveBeenCalled();
    expect(getProducts()).toEqual(beforeProducts);
    expect(getCatalogImportItems({ requireConfirmation: true })).toEqual(beforeListings);
  });
  it('groups selected listings after completing a new Active Master', () => {
    const onOpenMaster = vi.fn();
    const onChanged = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={onOpenMaster} />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    fireEvent.click(screen.getByRole('button', { name: 'Create one Master' }));
    const dialog = within(screen.getByRole('region', { name: 'Create one Master' }));
    expect(dialog.getByRole('button', { name: 'Create, activate & link' })).toBeDisabled();
    fireEvent.click(dialog.getByRole('checkbox', { name: /I checked/ }));

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(onChanged).toHaveBeenCalledOnce();
    expect(onOpenMaster).not.toHaveBeenCalled();
    const product = getProductById(onChanged.mock.calls[0][0][0])!;
    expect(product.status).toBe('published');
    expect(product.channels).toHaveLength(2);
    expect(screen.getByText('No listings waiting for confirmation')).toBeVisible();
  });
  it('distinguishes an empty search from an empty intake queue', () => {
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={vi.fn()} />);
    fireEvent.change(screen.getByRole('textbox', { name: 'Search shop listings' }), { target: { value: 'not-a-listing' } });
    expect(screen.getByText('No listings match your search')).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Clear search' }));
    expect(screen.getAllByRole('button', { name: 'Choose Master' })).toHaveLength(2);
  });
  it('returns to the queue after link-only confirmation and exposes the unchanged Draft', () => {
    const master = { ...getProducts()[0], ...readyMasterFields(), id: 'ui-sequential-master', name: 'Sequential Master', sku_code: 'UI-SEQUENTIAL', brand: 'Test Brand', has_variants: false, product_type: 'single', skus: [], channels: [], import_sources: [], status: 'draft', import_result: undefined } as Product;
    addProduct(master);
    saveCatalogImportItems(getCatalogImportItems({ requireConfirmation: true }).map(item => ({ ...item, channelSku: master.sku_code, brand: master.brand, suggestedProductId: master.id, status: 'suggested' })));
    const onChanged = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={vi.fn()} stayInQueue />);
    fireEvent.click(screen.getAllByRole('button', { name: 'Review suggestion' })[0]);
    expect(screen.getByRole('group', { name: 'Source listing' })).toHaveTextContent('Shop 0');
    fireEvent.click(screen.getByRole('button', { name: 'Link to this Master' }));
    expect(onChanged).toHaveBeenCalledOnce();
    expect(screen.getByRole('button', { name: 'View updated Master' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Review suggestion' }));
    expect(screen.getByRole('group', { name: 'Source listing' })).toHaveTextContent('Shop 1');
    expect(screen.getByText('1 listing left to review')).toBeVisible();
    expect(screen.getByText('Not confirmed')).toBeVisible();
    expect(getProductById(master.id)?.channels).toHaveLength(1);
    fireEvent.click(screen.getByRole('button', { name: 'Link to this Master' }));
    expect(onChanged).toHaveBeenCalledTimes(2);
    expect(getProductById(master.id)?.status).toBe('draft');
    expect(getProductById(master.id)?.channels).toHaveLength(2);
    expect(screen.getByText('No listings waiting for confirmation')).toBeVisible();
  });
  it('creates an Active Master and returns to the queue without navigating away', () => {
    const onOpenMaster = vi.fn();
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={onOpenMaster} stayInQueue />);
    fireEvent.click(screen.getAllByRole('button', { name: 'Choose Master' })[0]);
    fireEvent.click(screen.getByRole('button', { name: 'Create new Master' }));

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(onOpenMaster).not.toHaveBeenCalled();
    expect(screen.getByRole('heading', { name: '1 listing to review' })).toBeVisible();
    const product = getProducts().find(item => !ids.has(item.id))!;
    expect(product.status).toBe('published');
    expect(product.channels).toHaveLength(1);
    expect(screen.getByRole('button', { name: 'View updated Master' })).toBeVisible();
    expect(screen.getByRole('heading', { name: '1 listing to review' })).toBeVisible();
  });
  it('returns without saving or advancing and keeps pending listings in the queue', () => {
    const onChanged = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={vi.fn()} stayInQueue />);
    fireEvent.click(screen.getAllByRole('button', { name: 'Choose Master' })[0]);
    expect(screen.queryByRole('button', { name: 'Review later' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Back to listings' }));
    expect(screen.getByRole('heading', { name: '2 listings to review' })).toBeVisible();
    expect(screen.queryByRole('group', { name: 'Source listing' })).not.toBeInTheDocument();
    expect(screen.getByRole('checkbox', { name: 'Select listing UI-a from Shop 0' })).toBeChecked();
    expect(onChanged).not.toHaveBeenCalled();
    expect(getCatalogImportItems({ requireConfirmation: true }).every(item => !item.confirmed)).toBe(true);
  });
  it('does not auto-advance into listings outside the current search', () => {
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={vi.fn()} stayInQueue />);
    fireEvent.change(screen.getByRole('textbox', { name: 'Search shop listings' }), { target: { value: 'Shop 0' } });
    fireEvent.click(screen.getByRole('button', { name: 'Choose Master' }));
    fireEvent.click(screen.getByRole('button', { name: 'Create new Master' }));

    completeListingDetails(); fireEvent.click(screen.getByRole('button', { name: 'Create, activate & link' }));
    expect(screen.getByText('No listings match your search')).toBeVisible();
    expect(screen.getByRole('textbox', { name: 'Search shop listings' })).toHaveValue('Shop 0');
    expect(screen.getByRole('heading', { name: '1 listing to review' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Clear search' }));
    expect(screen.getByText('Shop 1')).toBeVisible();
  });
  it('shows one complete queue and exposes suggested confirmation only for an eligible selection', () => {
    const master = { ...getProducts()[0], ...readyMasterFields(), id: 'ui-batch-a', name: 'Master Alpha', sku_code: 'UI-ALPHA', brand: 'Test Brand', has_variants: false, product_type: 'single', skus: [], channels: [], status: 'draft', import_result: undefined } as Product;
    addProduct(master);
    const items = getCatalogImportItems({ requireConfirmation: true });
    saveCatalogImportItems([{ ...items[0], channelSku: master.sku_code, brand: master.brand, status: 'suggested', suggestedProductId: master.id, confidence: 99 }, items[1]]);
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={vi.fn()} stayInQueue />);
    expect(screen.getByRole('heading', { name: '2 listings to review' })).toBeVisible();
    expect(screen.queryByRole('group', { name: 'Listing review filters' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /All listings|Suggested matches|Needs checking|Select eligible suggestions/ })).not.toBeInTheDocument();
    expect(screen.queryByText(/eligible for bulk confirmation/)).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Choose Master' })).toBeVisible();
    expect(screen.getByRole('button', { name: 'Review suggestion' })).toBeVisible();
    expect(screen.getByText('Master Alpha')).toBeVisible();
    expect(screen.getByText('No suggestion yet')).toBeVisible();
    expect(screen.queryByRole('group', { name: 'Selected listing actions' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    expect(screen.queryByRole('button', { name: /Review suggested links/ })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Link to one Master' })).toBeEnabled();
    expect(screen.getByRole('button', { name: 'Create one Master' })).toBeEnabled();
    expect(screen.queryByRole('button', { name: 'Review selected listings' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select listing UI-b from Shop 1' }));
    expect(screen.getByRole('button', { name: 'Review suggested links (1)' })).toBeEnabled();
    fireEvent.change(screen.getByRole('textbox', { name: 'Search shop listings' }), { target: { value: 'missing' } });
    expect(screen.queryByRole('group', { name: 'Selected listing actions' })).not.toBeInTheDocument();
    expect(screen.getByRole('heading', { name: '2 listings to review' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Clear search' }));
    expect(screen.getAllByRole('button', { name: /^(Choose Master|Review suggestion)$/ })).toHaveLength(2);
  });
  it('keeps flagged suggestions in the same queue with their reasons and manual actions', () => {
    const master = { ...getProducts()[0], ...readyMasterFields(), id: 'ui-flagged-master', name: 'Flagged Master', sku_code: 'UI-FLAGGED', brand: 'Test Brand', has_variants: false, product_type: 'single', skus: [], channels: [], status: 'draft', import_result: undefined } as Product;
    addProduct(master);
    saveCatalogImportItems(getCatalogImportItems({ requireConfirmation: true }).map((item, index) => ({ ...item, channelSku: master.sku_code, brand: index === 0 ? 'Different Brand' : master.brand, variants: index === 0 ? 1 : 3, status: 'suggested', suggestedProductId: master.id, confidence: 99 })));
    render(<ProductListingIntake onChanged={vi.fn()} onOpenMaster={vi.fn()} stayInQueue />);
    expect(screen.getByRole('heading', { name: '2 listings to review' })).toBeVisible();
    expect(screen.getByText('Brand differs — review individually')).toBeVisible();
    expect(screen.getByText('Variant-SKU matching required')).toBeVisible();
    expect(screen.getAllByRole('button', { name: 'Review suggestion' })).toHaveLength(2);
    expect(screen.queryByText(/eligible for bulk confirmation/)).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    expect(screen.queryByRole('button', { name: /Review suggested links/ })).not.toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', { name: 'Review suggestion' })[0]);
    expect(screen.getByRole('region', { name: 'Compare product details' })).toBeVisible();
    expect(screen.getByText('Suggested Product Master')).toBeVisible();
    expect(screen.getByRole('button', { name: 'Link to this Master' })).toBeEnabled();
    expect(screen.getByRole('group', { name: 'Differences to check' })).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Back to listings' }));
    fireEvent.click(screen.getAllByRole('button', { name: 'Review suggestion' })[1]);
    expect(screen.getByText('SKU mapping needs review')).toBeVisible();
    expect(screen.getByRole('button', { name: 'Link to this Master' })).toBeDisabled();
    expect(getCatalogImportItems({ requireConfirmation: true }).every(item => !item.confirmed)).toBe(true);
  });
  it('previews distinct Listing-to-Master pairs and saves only after explicit acknowledgement', () => {
    const masters = ['Alpha', 'Beta'].map(name => ({ ...getProducts()[0], ...readyMasterFields(), id: `ui-batch-${name}`, name: `Master ${name}`, description: '', images: [], sku_code: `UI-${name}`, brand: 'Test Brand', has_variants: false, product_type: 'single', skus: [], channels: [], status: 'draft', import_result: undefined } as Product));
    masters.forEach(master => addProduct(master));
    saveCatalogImportItems(getCatalogImportItems({ requireConfirmation: true }).map((item, index) => ({ ...item, title: `Listing ${index}`, channelSku: masters[index].sku_code, brand: masters[index].brand, status: 'suggested', suggestedProductId: masters[index].id, confidence: 99 })));
    const onChanged = vi.fn();
    const onOpenMaster = vi.fn();
    render(<ProductListingIntake onChanged={onChanged} onOpenMaster={onOpenMaster} stayInQueue />);
    fireEvent.click(screen.getByRole('checkbox', { name: 'Select visible shop listings' }));
    fireEvent.click(screen.getByRole('button', { name: 'Review suggested links (2)' }));
    let dialog = within(screen.getByRole('dialog', { name: 'Review suggested links' }));
    expect(dialog.getByRole('button', { name: 'Confirm links' })).toBeDisabled();
    const pairs = within(dialog.getByRole('list', { name: 'Listing to Master pairs' })).getAllByRole('listitem');
    expect(pairs[0]).toHaveTextContent('Listing 0');
    expect(pairs[0]).toHaveTextContent('Master Alpha');
    expect(pairs[1]).toHaveTextContent('Master Beta');
    fireEvent.click(dialog.getByRole('button', { name: 'Back to review' }));
    masters.forEach(master => expect(getProductById(master.id)?.channels).toEqual([]));
    fireEvent.click(screen.getByRole('button', { name: 'Review suggested links (2)' }));
    dialog = within(screen.getByRole('dialog', { name: 'Review suggested links' }));
    fireEvent.click(dialog.getByRole('checkbox', { name: /I reviewed every/ }));
    expect(dialog.queryByLabelText('Complete Master details')).not.toBeInTheDocument();
    fireEvent.click(dialog.getByRole('button', { name: 'Confirm links' }));
    expect(onChanged).toHaveBeenCalledOnce();
    expect(onOpenMaster).not.toHaveBeenCalled();
    masters.forEach(master => {
      expect(getProductById(master.id)?.channels).toHaveLength(1);
      expect(getProductById(master.id)).toMatchObject({ status: 'draft', images: [], description: '' });
    });
    expect(screen.getByText('No listings waiting for confirmation')).toBeVisible();
  });
});
