import { BarChart3, CheckCircle2, MessageSquareText, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { WorkspacePageHeader } from '@/components/system/WorkspacePageHeader';

export function QuickRepliesPage() {
  const replies = [['Product availability', 'This item is currently available at {{warehouse}}.'], ['Shipping ETA', 'Delivery is estimated within {{eta}} business days.'], ['Order confirmation', 'Your order {{order_id}} has been confirmed.']];
  return <div className="space-y-5 p-4 md:p-6"><WorkspacePageHeader title="Quick Reply Templates" description="Manage approved responses used by agents in Prime Inbox Workspace." icon={MessageSquareText} actions={<Button>Add Template</Button>} /><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input placeholder="Search templates..." className="pl-9" /></div><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{replies.map(([name, content]) => <div key={name} className="flex items-center gap-4 p-4"><CheckCircle2 className="size-4 text-emerald-500" /><div className="flex-1"><p className="text-sm font-semibold text-slate-900">{name}</p><p className="mt-1 text-xs text-slate-500">{content}</p></div><Button variant="ghost" size="sm">Edit</Button></div>)}</div></section></div>;
}

export function CsAnalyticsPage() {
  const metrics = [['First response time', '2m 18s', '↓ 14%'], ['Resolution time', '18m 42s', '↓ 8%'], ['CSAT', '94.6%', '↑ 2.1%'], ['Conversations handled', '1,284', '↑ 12%']];
  return <div className="space-y-5 p-4 md:p-6"><WorkspacePageHeader title="Customer Service Analytics" description="Measure response quality and agent performance across social conversation channels." icon={BarChart3} /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, trend]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold tabular-nums text-slate-900">{value}</p><p className="mt-1 text-xs font-semibold text-emerald-700">{trend} vs last period</p></article>)}</section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Channel performance</h2><div className="mt-5 space-y-4">{[['Facebook', 92], ['Zalo', 86], ['Shopee Chat', 74]].map(([name, value]) => <div key={name as string}><div className="flex justify-between text-sm"><span className="font-medium text-slate-700">{name}</span><span className="tabular-nums text-slate-500">{value}% SLA met</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${value}%` }} /></div></div>)}</div></section></div>;
}
