import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Check, CheckCircle2, CircleDollarSign, Clock3, CreditCard, Search, X } from 'lucide-react';
import { toast } from 'sonner';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { WorkspacePageHeader } from '@/components/system/WorkspacePageHeader';
import { billingPlans, featureGroups, formatVnd, planById, seedBillingRequests, type BillingPlan, type BillingRequest, type BillingRequestType, type PlanId } from '@/lib/plan-billing';
import { cn } from '@/lib/utils';

const currentPlanId: PlanId = 'pro';
const planRank: Record<PlanId, number> = { freemium: 0, starter: 1, standard: 2, pro: 3 };
const history = [
  { planId: 'pro' as PlanId, status: 'Current', start: '18 Aug 2026', end: '17 Aug 2027' },
  { planId: 'standard' as PlanId, status: 'Used', start: '12 Jun 2026', end: '17 Aug 2026' },
  { planId: 'starter' as PlanId, status: 'Used', start: '01 Mar 2026', end: '11 Jun 2026' },
];

function PlanMark({ id, size = 'md' }: { id: PlanId; size?: 'sm' | 'md' }) {
  const colors = { freemium: 'from-sky-400 to-blue-600', starter: 'from-cyan-400 to-blue-600', standard: 'from-violet-400 to-blue-600', pro: 'from-fuchsia-400 to-blue-600' };
  return <span aria-hidden className={cn('grid shrink-0 place-items-center rounded-xl bg-gradient-to-br shadow-sm', colors[id], size === 'sm' ? 'size-10' : 'size-14')}><span className="h-1/2 w-1/2 rounded-full border-2 border-white/80" /></span>;
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = { Current: 'border-primary/30 bg-primary/10 text-primary', Used: 'border-border bg-muted text-muted-foreground', Approved: 'border-emerald-300 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300', Pending: 'border-amber-300 bg-amber-50 text-amber-700', Rejected: 'border-red-300 bg-red-50 text-red-700', Failed: 'border-orange-300 bg-orange-50 text-orange-700', Cancelled: 'border-border bg-muted text-muted-foreground' };
  return <Badge variant="outline" className={styles[status]}>{status}</Badge>;
}

function Overview({ onViewPlans, onTerminate }: { onViewPlans: () => void; onTerminate: () => void }) {
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.05fr)_minmax(360px,.95fr)]">
    <Card className="overflow-hidden shadow-none"><div className="h-1 bg-primary" /><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardDescription>Current plan</CardDescription><CardTitle className="mt-2 flex items-center gap-3 text-xl"><PlanMark id="pro" size="sm" />Prime OS Pro</CardTitle></div><StatusBadge status="Current" /></div></CardHeader><CardContent className="space-y-6"><div><p className="text-3xl font-bold tracking-tight text-primary">{formatVnd(planById('pro').monthlyPrice)}<span className="text-base font-medium text-muted-foreground"> / month</span></p><p className="mt-2 text-sm text-muted-foreground">Your subscription renews automatically on 18 August 2027.</p></div><dl className="grid gap-4 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Start date</dt><dd className="mt-1 text-sm font-semibold">18 Aug 2026, 09:15</dd></div><div><dt className="text-xs text-muted-foreground">End date</dt><dd className="mt-1 text-sm font-semibold">17 Aug 2027, 23:59</dd></div><div><dt className="text-xs text-muted-foreground">Remaining</dt><dd className="mt-1 text-sm font-semibold">11 months 8 days</dd></div><div><dt className="text-xs text-muted-foreground">Waiver</dt><dd className="mt-1 text-sm font-semibold">No</dd></div></dl><div className="flex flex-col gap-3 rounded-xl border border-primary/30 bg-primary/5 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Manage your subscription</p><p className="text-xs text-muted-foreground">Compare plan limits or schedule a change.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={onTerminate}>Terminate</Button><Button onClick={onViewPlans}>Change plan</Button></div></div></CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle className="text-lg">Plan history</CardTitle><CardDescription>Your current and previous subscription periods.</CardDescription></CardHeader><CardContent className="space-y-3">{history.map((item) => { const plan = planById(item.planId); return <div key={`${item.planId}-${item.start}`} className={cn('flex items-center gap-3 rounded-xl border p-4', item.status === 'Current' && 'border-primary/30 bg-primary/5')}><PlanMark id={item.planId} size="sm" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">Prime OS {plan.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.start} – {item.end}</p></div><StatusBadge status={item.status} /></div>; })}</CardContent></Card>
  </div>;
}

function FeatureComparison({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] max-w-6xl overflow-y-auto p-0 [&>button]:z-50 [&>button]:grid [&>button]:size-9 [&>button]:place-items-center [&>button]:rounded-md [&>button]:border [&>button]:bg-background [&>button]:opacity-100 [&>button]:shadow-sm"><DialogHeader className="sticky top-0 z-40 border-b bg-background px-6 py-5 pr-16"><DialogTitle>Compare all plan features</DialogTitle><DialogDescription>Review limits and capabilities before changing your subscription.</DialogDescription></DialogHeader><div className="hidden px-6 pb-6 md:block"><Table className="min-w-[850px]"><TableHeader><TableRow><TableHead className="w-[38%]">Capability</TableHead>{billingPlans.map((plan) => <TableHead key={plan.id} className="text-center">{plan.name}</TableHead>)}</TableRow></TableHeader><TableBody>{featureGroups.flatMap((group) => [<TableRow key={group.name} className="bg-primary text-primary-foreground hover:bg-primary"><TableCell colSpan={5} className="py-3 font-semibold">{group.name}</TableCell></TableRow>, ...group.features.map((feature) => <TableRow key={`${group.name}-${feature.name}`}><TableCell className="font-medium">{feature.name}{feature.badge ? <Badge className="ml-2" variant="secondary">{feature.badge}</Badge> : null}</TableCell>{billingPlans.map((plan) => { const value = feature.values[plan.id]; return <TableCell key={plan.id} className="text-center">{value === true ? <CheckCircle2 className="mx-auto size-4 text-primary" aria-label="Included" /> : value === false ? <span className="text-muted-foreground" aria-label="Not included">—</span> : <span className="text-xs font-semibold">{value}</span>}</TableCell>; })}</TableRow>)])}</TableBody></Table></div><Accordion type="multiple" className="px-5 pb-5 md:hidden">{featureGroups.map((group) => <AccordionItem key={group.name} value={group.name}><AccordionTrigger className="text-left text-sm">{group.name}</AccordionTrigger><AccordionContent className="space-y-3">{group.features.map((feature) => <div key={feature.name} className="rounded-lg border p-3"><p className="text-sm font-semibold">{feature.name}</p><div className="mt-2 grid grid-cols-2 gap-2">{billingPlans.map((plan) => <span key={plan.id} className="flex items-center justify-between rounded bg-muted px-2 py-1 text-xs"><span>{plan.name}</span><span>{feature.values[plan.id] === true ? '✓' : feature.values[plan.id] === false ? '—' : feature.values[plan.id]}</span></span>)}</div></div>)}</AccordionContent></AccordionItem>)}</Accordion></DialogContent></Dialog>;
}

function Plans({ onRequest }: { onRequest: (plan: BillingPlan, type: BillingRequestType) => void }) {
  const [compareOpen, setCompareOpen] = useState(false);
  return <><div className="mb-4 flex justify-end"><Button variant="outline" onClick={() => setCompareOpen(true)}>Compare all features</Button></div><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{billingPlans.map((plan) => { const current = plan.id === currentPlanId; const type: BillingRequestType = planRank[plan.id] > planRank[currentPlanId] ? 'Upgrade' : 'Downgrade'; return <Card key={plan.id} className={cn('flex min-h-[470px] flex-col overflow-hidden shadow-none', current && 'border-primary bg-primary text-primary-foreground')}><CardHeader><PlanMark id={plan.id} /><CardTitle className="mt-4 text-2xl">Prime OS {plan.name}</CardTitle><CardDescription className={current ? 'text-primary-foreground/75' : undefined}>{plan.description}</CardDescription></CardHeader><CardContent className="flex flex-1 flex-col"><ul className="space-y-3">{plan.highlights.map((item) => <li key={item} className="flex gap-2 text-sm"><CheckCircle2 className={cn('mt-0.5 size-4 shrink-0 text-primary', current && 'text-primary-foreground')} />{item}</li>)}</ul><div className="mt-auto pt-8"><p className="mb-4 text-xl font-bold">{formatVnd(plan.monthlyPrice)}{plan.monthlyPrice ? <span className="text-sm font-medium opacity-70"> / month</span> : null}</p><Button className={cn('w-full', current && 'bg-white/20 text-white hover:bg-white/30')} variant={current ? 'secondary' : type === 'Downgrade' ? 'outline' : 'default'} disabled={current} onClick={() => onRequest(plan, type)}>{current ? 'Current plan' : type}</Button></div></CardContent></Card>; })}</div><FeatureComparison open={compareOpen} onOpenChange={setCompareOpen} /></>;
}

function RequestHistory({ requests }: { requests: BillingRequest[] }) {
  const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [status, setStatus] = useState('all');
  const filtered = useMemo(() => requests.filter((item) => item.id.toLowerCase().includes(query.toLowerCase()) && (type === 'all' || item.type === type) && (status === 'all' || item.status === status)), [query, requests, status, type]);
  return <Card className="shadow-none"><CardHeader><CardTitle>Request history</CardTitle><CardDescription>Track subscription changes submitted for this workspace.</CardDescription></CardHeader><CardContent><div className="mb-4 grid gap-3 lg:grid-cols-[minmax(260px,1fr)_220px_220px]"><div className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><Input aria-label="Search by request ID" className="pl-9" placeholder="Search by request ID" value={query} onChange={(event) => setQuery(event.target.value)} /></div><Select value={type} onValueChange={setType}><SelectTrigger aria-label="Request type"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All request types</SelectItem><SelectItem value="Upgrade">Upgrade</SelectItem><SelectItem value="Downgrade">Downgrade</SelectItem><SelectItem value="Terminate">Terminate</SelectItem></SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Request status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{['Pending', 'Approved', 'Rejected', 'Failed', 'Cancelled'].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><Table className="min-w-[850px]"><TableHeader><TableRow><TableHead>Request ID</TableHead><TableHead>Requested plan</TableHead><TableHead>Type</TableHead><TableHead>Effective date</TableHead><TableHead>Status</TableHead><TableHead>Request date</TableHead></TableRow></TableHeader><TableBody>{filtered.map((item) => <TableRow key={item.id}><TableCell className="font-mono text-xs">{item.id}</TableCell><TableCell><span className="flex items-center gap-2 font-medium"><PlanMark id={item.planId} size="sm" />{planById(item.planId).name}</span></TableCell><TableCell><Badge variant="secondary">{item.type}</Badge></TableCell><TableCell>{new Date(item.effectiveAt).toLocaleDateString('vi-VN')}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{new Date(item.requestedAt).toLocaleString('vi-VN')}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length ? <div className="py-12 text-center text-sm text-muted-foreground">No requests match these filters.</div> : null}</CardContent></Card>;
}

export default function PlanBillingPage() {
  const [params, setParams] = useSearchParams(); const requestedTab = params.get('tab'); const tab = requestedTab === 'plans' || requestedTab === 'requests' ? requestedTab : 'overview';
  const [requests, setRequests] = useState(seedBillingRequests); const [selection, setSelection] = useState<{ plan: BillingPlan; type: BillingRequestType } | null>(null);
  const submit = () => { if (!selection) return; const now = new Date(); const immediate = selection.type === 'Upgrade'; const effective = immediate ? now : new Date(now.getFullYear(), now.getMonth() + 1, 1); setRequests((items) => [{ id: `${selection.type === 'Upgrade' ? 'UP' : 'DN'}${Date.now()}`, planId: selection.plan.id, type: selection.type, status: 'Pending', requestedAt: now.toISOString(), effectiveAt: effective.toISOString() }, ...items]); toast.success('Subscription request submitted'); setSelection(null); setParams({ tab: 'requests' }); };
  return <main className="min-h-full bg-[hsl(var(--surface-stage))] p-4 pb-24 md:p-6"><div className="mx-auto max-w-[1600px] space-y-5"><WorkspacePageHeader title="Plan & Billing" description="Manage your Prime OS subscription, compare capabilities, and track change requests." icon={CreditCard} /><Tabs value={tab} onValueChange={(value) => setParams(value === 'overview' ? {} : { tab: value })}><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl border bg-card p-1.5"><TabsTrigger value="overview" className="min-h-10"><CircleDollarSign className="size-4" />Overview</TabsTrigger><TabsTrigger value="plans" className="min-h-10"><CreditCard className="size-4" />Plans</TabsTrigger><TabsTrigger value="requests" className="min-h-10"><Clock3 className="size-4" />Request history</TabsTrigger></TabsList><TabsContent value="overview" className="mt-5"><Overview onViewPlans={() => setParams({ tab: 'plans' })} onTerminate={() => setSelection({ plan: planById(currentPlanId), type: 'Terminate' })} /></TabsContent><TabsContent value="plans" className="mt-5"><Plans onRequest={(plan, type) => setSelection({ plan, type })} /></TabsContent><TabsContent value="requests" className="mt-5"><RequestHistory requests={requests} /></TabsContent></Tabs></div><Dialog open={Boolean(selection)} onOpenChange={(open) => !open && setSelection(null)}><DialogContent><DialogHeader><DialogTitle>Confirm {selection?.type.toLowerCase()}</DialogTitle><DialogDescription>{selection?.type === 'Upgrade' ? 'The upgrade takes effect immediately.' : selection?.type === 'Terminate' ? 'Your subscription remains active until the end of the current billing cycle.' : 'The downgrade takes effect at the start of your next billing cycle.'}</DialogDescription></DialogHeader>{selection ? <div className="space-y-4"><div className="flex items-center gap-3 rounded-xl border p-4"><PlanMark id={selection.plan.id} size="sm" /><div><p className="font-semibold">Prime OS {selection.plan.name}</p><p className="text-sm text-muted-foreground">{formatVnd(selection.plan.monthlyPrice)} / month</p></div></div>{selection.type !== 'Upgrade' ? <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">{selection.type === 'Terminate' ? 'Access will end when the current billing cycle expires.' : 'Your workspace limits will change when this request becomes effective. Review the feature comparison before continuing.'}</div> : null}</div> : null}<DialogFooter><Button variant="outline" onClick={() => setSelection(null)}><X className="size-4" />Cancel</Button><Button onClick={submit}><Check className="size-4" />Submit request</Button></DialogFooter></DialogContent></Dialog></main>;
}
