import { Link2, PackagePlus, SlidersHorizontal } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { CatalogStrategy } from '@/lib/channel-integrations-api';

const strategies = [{ value: 'AUTO_MATCH_SKU' as const, title: 'Auto-match by SKU', detail: 'Recommended · Link exact SKU matches and flag exceptions.', icon: Link2 }, { value: 'CREATE_NEW_MASTERS' as const, title: 'Create new Master Products', detail: 'Create a master record for every unmatched channel listing.', icon: PackagePlus }, { value: 'MANUAL_LATER' as const, title: 'Configure manually later', detail: 'Connect now and review every catalog mapping before publishing.', icon: SlidersHorizontal }];

export function Step4CatalogSync({ value, onChange }: { value: CatalogStrategy; onChange: (value: CatalogStrategy) => void }) {
  return <div className="space-y-3"><p className="text-sm text-muted-foreground">Choose how existing channel listings should map to the Prime OS Master Catalog.</p>{strategies.map(({ value: option, title, detail, icon: Icon }) => <button key={option} type="button" onClick={() => onChange(option)} className={cn('flex w-full items-start gap-3 rounded-xl border p-4 text-left transition', value === option ? 'border-primary bg-primary/[0.05] ring-1 ring-primary/20' : 'hover:bg-muted/50')}><span className={cn('mt-0.5 grid size-9 shrink-0 place-items-center rounded-lg', value === option ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground')}><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{title}</span><span className={cn('size-4 rounded-full border-2', value === option ? 'border-[5px] border-primary' : 'border-muted-foreground/40')} /></span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{detail}</span></span></button>)}</div>;
}
