import { Link2, PackagePlus, SlidersHorizontal } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { CatalogStrategy } from '@/lib/channel-integrations-api';

const strategies = [{ value: 'AUTO_MATCH_SKU' as const, title: 'Auto-match & review', detail: 'Recommended · Suggest Product Masters using SKU and identifiers. You review every decision before it is applied.', icon: Link2 }, { value: 'CREATE_NEW_MASTERS' as const, title: 'Prepare drafts for unmatched listings', detail: 'Suggest matches first, then prepare Product Master drafts for unmatched listings in the review workspace.', icon: PackagePlus }, { value: 'MANUAL_LATER' as const, title: 'Import now, map later', detail: 'Bring listings into the review queue without linking or creating Product Masters.', icon: SlidersHorizontal }];

export function Step4CatalogSync({ value, onChange }: { value: CatalogStrategy; onChange: (value: CatalogStrategy) => void }) {
  return <div className="space-y-3"><div><p className="text-sm font-semibold">How should Prime OS prepare imported listings?</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Nothing is linked or created until you confirm it in Catalog Import Review.</p></div>{strategies.map(({ value: option, title, detail, icon: Icon }) => <button key={option} type="button" onClick={() => onChange(option)} className={cn('flex min-h-20 w-full items-start gap-3 rounded-xl border p-4 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring', value === option ? 'border-primary bg-primary/[0.05] ring-1 ring-primary/20' : 'hover:bg-muted/50')} aria-pressed={value === option}><span className={cn('mt-0.5 grid size-9 shrink-0 place-items-center rounded-lg', value === option ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground')}><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{title}</span><span className={cn('size-4 rounded-full border-2', value === option ? 'border-[5px] border-primary' : 'border-muted-foreground/40')} /></span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{detail}</span></span></button>)}</div>;
}
