import { PackageCheck, RotateCcw, Truck, Warehouse } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cn } from '@/lib/utils';
import type { ChannelWarehouse } from '@/lib/channel-integrations-api';

export function Step3WarehouseConfig({ warehouses, warehouseId, services, pickup, returns, onWarehouseChange, onServiceChange, onPickupChange, onReturnChange }: { warehouses: ChannelWarehouse[]; warehouseId: string; services: { price: boolean; stock: boolean; orders: boolean }; pickup: boolean; returns: boolean; onWarehouseChange: (value: string) => void; onServiceChange: (key: 'price' | 'stock' | 'orders', value: boolean) => void; onPickupChange: (value: boolean) => void; onReturnChange: (value: boolean) => void }) {
  const serviceItems = [{ key: 'price' as const, label: 'Price sync', detail: 'Publish approved prices', icon: PackageCheck }, { key: 'stock' as const, label: 'Stock sync', detail: 'Share available inventory', icon: Warehouse }, { key: 'orders' as const, label: 'Orders sync', detail: 'Import new orders', icon: Truck }];
  return <div className="space-y-5"><div><label className="text-sm font-medium">Physical warehouse</label><Select value={warehouseId} onValueChange={onWarehouseChange}><SelectTrigger className="mt-2"><SelectValue placeholder="Select the fulfillment warehouse" /></SelectTrigger><SelectContent>{warehouses.map((item) => <SelectItem key={item.id} value={item.id}>{item.name} · {item.code}</SelectItem>)}</SelectContent></Select><p className="mt-2 text-xs text-muted-foreground">Channel inventory and imported orders will use this location by default.</p></div><div><p className="text-sm font-medium">Active sync services</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{serviceItems.map(({ key, label, detail, icon: Icon }) => <label key={key} className={cn('flex cursor-pointer gap-3 rounded-xl border p-3 transition', services[key] ? 'border-primary/40 bg-primary/[0.04]' : 'hover:bg-muted/50')}><Checkbox checked={services[key]} onCheckedChange={(value) => onServiceChange(key, value === true)} /><span><Icon className="mb-2 size-4 text-primary" /><span className="block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{detail}</span></span></label>)}</div></div><div className="grid gap-2 sm:grid-cols-2"><label className="flex cursor-pointer items-start gap-3 rounded-xl border p-4"><Checkbox checked={pickup} onCheckedChange={(value) => onPickupChange(value === true)} /><span><span className="block text-sm font-semibold">Default pickup location</span><span className="mt-1 block text-xs text-muted-foreground">Use for carrier collection.</span></span></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border p-4"><Checkbox checked={returns} onCheckedChange={(value) => onReturnChange(value === true)} /><span><span className="block text-sm font-semibold">Default return location</span><span className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><RotateCcw className="size-3" />Route channel returns here.</span></span></label></div></div>;
}
