import { ExternalLink, Loader2, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { AvailablePlatform } from '@/lib/channel-integrations-api';

export function Step2StoreAuth({ platform, storeName, region, authorizing, error, onStoreNameChange, onRegionChange, onAuthorize }: { platform: AvailablePlatform; storeName: string; region: string; authorizing: boolean; error: string; onStoreNameChange: (value: string) => void; onRegionChange: (value: string) => void; onAuthorize: () => void }) {
  return <div className="space-y-5"><div className="rounded-xl border border-primary/20 bg-primary/[0.04] p-4"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-lg text-white" style={{ backgroundColor: platform.color }}><ShieldCheck className="size-5" /></span><div><p className="text-sm font-semibold">Authorize {platform.name}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Prime OS requests catalog, inventory, price, and order permissions. Credentials are never displayed in this wizard.</p></div></div></div><div className="grid gap-4 sm:grid-cols-[1fr_180px]"><div><label htmlFor="store-name" className="text-sm font-medium">Store name</label><Input id="store-name" value={storeName} onChange={(event) => onStoreNameChange(event.target.value)} placeholder={`e.g. Prime ${platform.name} Official Store`} className="mt-2" /></div><div><label className="text-sm font-medium">Region</label><Select value={region} onValueChange={onRegionChange}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{platform.regions.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div>{error ? <p role="alert" className="rounded-lg border border-destructive/25 bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p> : null}<Button type="button" className="w-full" disabled={!storeName.trim() || authorizing} onClick={onAuthorize}>{authorizing ? <Loader2 className="size-4 animate-spin" /> : <ExternalLink className="size-4" />}{authorizing ? 'Waiting for authorization...' : 'Authorize & Continue'}</Button><p className="text-center text-xs text-muted-foreground">A secure authorization window will open. Keep this window open until it completes.</p></div>;
}
