import { Search, Store } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import type { AvailablePlatform, ChannelCategory } from '@/lib/channel-integrations-api';

const categories: Array<'All' | ChannelCategory> = ['All', 'Marketplaces', 'E-Commerce/Web', 'Retail POS', 'Social'];

export function Step1ChannelCatalog({ platforms, query, category, onQueryChange, onCategoryChange, onSelect }: { platforms: AvailablePlatform[]; query: string; category: 'All' | ChannelCategory; onQueryChange: (value: string) => void; onCategoryChange: (value: 'All' | ChannelCategory) => void; onSelect: (platform: AvailablePlatform) => void }) {
  const visible = platforms.filter((platform) => (category === 'All' || platform.category === category) && platform.name.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="space-y-4"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input autoFocus value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search platforms..." className="pl-9" /></div><div className="scrollbar-none flex gap-1 overflow-x-auto">{categories.map((item) => <button key={item} type="button" onClick={() => onCategoryChange(item)} className={cn('min-h-9 shrink-0 rounded-lg px-3 text-xs font-semibold transition-colors', category === item ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground')}>{item}</button>)}</div><div className="grid max-h-[390px] gap-3 overflow-y-auto pr-1 sm:grid-cols-2">{visible.map((platform) => <button key={platform.id} type="button" onClick={() => onSelect(platform)} className="group flex min-h-24 items-center gap-3 rounded-xl border bg-card p-4 text-left transition hover:border-primary/40 hover:bg-primary/[0.03] hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid size-11 shrink-0 place-items-center rounded-xl text-white" style={{ backgroundColor: platform.color }}><Store className="size-5" /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-foreground">{platform.name}</span><span className="mt-1 block text-xs text-muted-foreground">{platform.category} · {platform.auth_type === 'OAUTH2' ? 'Secure OAuth' : 'Managed authorization'}</span></span></button>)}</div>{!visible.length ? <div className="py-12 text-center text-sm text-muted-foreground">No platforms match your search.</div> : null}</div>;
}
